template <typename Wrapper>
using T = GetConfig::Section::T
<
	Wrapper,
	GetConfig::Member::T
	<
		TCP::Config::T,
		false,
		TCP_CONFIG,
		TCP_CONFIG_DESCRIPTION
	>,
	GetConfig::Member::T
	<
		GetConfig::URI::Path::T,
		false,
		CA_PATH,
		CA_PATH_DESCRIPTION
	>,
	GetConfig::Member::T
	<
		GetConfig::URI::Host::T,
		true,
		SERVER_NAME,
		SERVER_NAME_DESCRIPTION
	>,
	GetConfig::Member::T
	<
		KeyPair::T,
		true,
		IDENTITY,
		IDENTITY_DESCRIPTION
	>,
	GetConfig::Member::T
	<
		GetConfig::Duration::T,
		false,
		HANDSHAKE_TIMEOUT,
		HANDSHAKE_TIMEOUT_DESCRIPTION,
		HANDSHAKE_TIMEOUT_DEFAULT
	>,
	GetConfig::Member::T
	<
		GetConfig::UInt::T,
		false,
		MAX_RECORD_SIZE,
		MAX_RECORD_SIZE_DESCRIPTION,
		MAX_RECORD_SIZE_DEFAULT
	>
>;
