using T = GetConfig::Section::T
<
	GetConfig::Member::T
	<
		GetConfig::UInt::T,
		false,
		INPUT_TIMEOUT,
		INPUT_TIMEOUT_DESCRIPTION,
		INPUT_TIMEOUT_DEFAULT
	>,
	GetConfig::Member::T
	<
		GetConfig::UInt::T,
		false,
		OUTPUT_TIMEOUT,
		OUTPUT_TIMEOUT_DESCRIPTION,
		OUTPUT_TIMEOUT_DEFAULT
	>,
	GetConfig::Member::T
	<
		GetConfig::UInt::T,
		false,
		ROUND_TRIP_TIMEOUT,
		ROUND_TRIP_TIMEOUT_DESCRIPTION,
		ROUND_TRIP_TIMEOUT_DEFAULT
	>,
	GetConfig::Member::T
	<
		GetConfig::UInt::T,
		false,
		TEMP_FILE_THRESHHOLD,
		TEMP_FILE_THRESHHOLD_DESCRIPTION,
		TEMP_FILE_THRESHHOLD_DEFAULT
	>,
	GetConfig::Member::T
	<
		TransferEncoding::Config::T,
		false,
		TRANSFER_ENCODING_CONFIG,
		TRANSFER_ENCODING_CONFIG_DESCRIPTION,
		TRANSFER_ENCODING_CONFIG_DEFAULT
	>
>;
